### ISSUE TITLE
Incompatibility with Bedrock Water when the water mode is "Tinted Water".

### ISSUE THREAD

**Issue by Lolothepro** [IPECTER/RTUShader#1]
Incompatibility with [Bedrock Water](https://www.planetminecraft.com/texture-pack/minecraft-bedrock-water-1-18-up/)

![2022-10-02_20 18 02](https://user-images.githubusercontent.com/68275908/193469639-b6cac8c2-1f90-44b6-8415-001bd93e43ae.png)

![2022-10-02_20 17 59](https://user-images.githubusercontent.com/68275908/193469642-8a13eb14-507d-48dc-8882-87f5902d98d9.png)

![2022-10-02_20 17 56](https://user-images.githubusercontent.com/68275908/193469645-7d96df8a-a05f-4dde-bb37-28764da4abb6.png)

**Comment by IPECTER** [comment]
The cause of this problem is the upstream shader, BSL.

and [Lux-Shader](https://github.com/TechDevOnGitHub/Lux-Shader) based on BSL too.
